name: v20_root_env
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - scipy
  - numpy>=1.20.0
  - jupyter
  - ipympl
  - matplotlib
  - uproot>=4.0
  - pip
  - pip:
    # works for regular pip packages
    - dress
    - Pillow
    - McStasScript
