name: v20_root_env
channels:
  - conda-forge
  - scipp
  - defaults
dependencies:
  - ipywidgets
  - ess
  - uproot
  - scipy
  - numpy
  - ipympl
  - ipython
  - jupyterlab
  - jupyterlab_widgets
  - plopp
  - pythreejs
  - pip
  - pip:
    # works for regular pip packages
    - Pillow
    - McStasScript
    - mpltoolbox