name: v20_root_env
channels:
  - conda-forge
  - scipp
  - defaults
dependencies:
  - ipywidgets
  - ess>=0.9.0
  - scipy
  - numpy>=1.20.0
  - ipympl
  - ipython
  - jupyterlab
  - jupyterlab_widgets
  - ipympl
  # - matplotlib-base
  - uproot>=4.0
  - plopp
  - pythreejs
  - pip
  - pip:
    # works for regular pip packages
    - Pillow
    - McStasScript
    - mpltoolbox